version: '3.8'

x-base-service: &base-service
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/usr/app
    - node_modules:/usr/app/node_modules
    - dist:/usr/app/dist
  depends_on:
    - minio
    - mongo
    - redis
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

services:
  api:
    <<: *base-service
    build:
      target: base
    ports:
      - "$API_PORT:$API_PORT"
    command: npm run dev:api
    healthcheck:
      test: wget http://api:$API_PORT -O /dev/null
      interval: 2m
      timeout: 10s
      retries: 5
      start_period: 2m
  worker:
    <<: *base-service
    build:
      target: worker
    command: npm run dev:worker
  socket:
    <<: *base-service
    build:
      target: base
    ports:
      - "$SOCKET_IO_PORT:$SOCKET_IO_PORT"
    command: npm run dev:websocket
  # TODO: https://min.io/docs/minio/linux/reference/minio-server/minio-server.html
  # Using MINIO_SECRET_KEY and MINIO_ACCESS_KEY are deprecated!!! Must change
  # several parts in the source code.
  minio:
    image: minio/minio:RELEASE.2022-09-17T00-09-45Z.hotfix.834a748f6
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    command: server /data --address :9001 --console-address :9002
    ports:
      - "9002:9002"
  mongo:
    image: mongo:jammy
  redis:
    image: redis:alpine3.17

volumes:
  node_modules:
  dist:
